### ISSUE TITLE
Lot of Auth & Server errors

### ISSUE THREAD

**Issue by matlink** [yeriomin/token-dispenser#14]
I was wondering how do you manage your google accounts?
When I look at the logs of my token dispenser instance, I can see a lot of 401 & 500 errors (GooglePlayException).
Do you know where it comes from and how to fix it?
Thanks.

**Comment by yeriomin** [comment]
I don't have errors now. I followed your advice a month ago and enabled 2-step auth and since then I didn't even have to reset the passwords.

This also depends on the specific url. Google API is NOT consistent. Auth requests answer with different errors than payload requests. Bulk details request, for example, does not even return an error if you use an invalid token, it just returns an empty list.

Is it random? What is in the request body?

**Comment by matlink** [comment]
It's not random, it happens by spikes.
However since I set-up every account with 2-step auth I got only 500 errors.
How can I inspect the response body? Have I to manually edit your google play api?

**Comment by yeriomin** [comment]
You can implement your own [HttpClientAdapter](https://github.com/yeriomin/play-store-api/blob/master/src/main/java/com/github/yeriomin/playstoreapi/HttpClientAdapter.java). I'm using [this one](https://github.com/yeriomin/play-store-api/blob/master/src/test/java/com/github/yeriomin/playstoreapi/OkHttpClientAdapter.java) for play-store-api tests, and [this one](https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/DebugHttpClientAdapter.java) for Yalp Store android app.

Or you could just make curl cron job.

**Comment by matlink** [comment]
The response body is "Error=ServerError"

**Comment by matlink** [comment]
Well, going back to your upstream branch seemed to resolve it. I might have changed too many things.
