### ISSUE TITLE
Possible to change device?

### ISSUE THREAD

**Issue by matlink** [yeriomin/token-dispenser#19]
Is there a way to change the arch of the requested apk? I would like for example token-dispenser to give tokens corresponding to a armeabi-v7a device.

**Comment by yeriomin** [comment]
Tokens are not linked to device info. Device info is inferred from `X-DFE-Device-Id` HTTP header supplied with every API request.

Token dispenser is used by Yalp Store which would give out identical search results and incompatible apps for all devices except Xiaomi MI5 (which is [used ](https://github.com/yeriomin/token-dispenser/blob/6b1428e9a36884aa6d46440b145efa2a12de8b6a/src/main/java/com/github/yeriomin/tokendispenser/TokenAc2dmResource.java#L63)in token dispenser just because the play-store-api library requires it).

**Comment by matlink** [comment]
It looks like the issues 'app not compatible with this device' I got comes from the fact that someone asked for a token with a different device just before I try to download an app with my token for another device. It looks like there is a race condition and that Google remembers the device-id corresponding to the token it gave.

**Comment by matlink** [comment]
Moreover, this issue never happens when I'm the only one to use a token-dispenser instance.
